/* Iteration 10 integration: state migration, choices, tutorials, autosave, keyboard UX */
const BaseGame = AO.Game;
AO.Game = class extends BaseGame {
  constructor(){super();this.talents=new AO.TalentSystem(this);this.reputation=new AO.ReputationSystem(this);this.crafting=new AO.CraftingSystem(this);window.addEventListener('keydown',ev=>{if(!this.state)return;const tag=document.activeElement?.tagName;if(tag==='INPUT'||tag==='TEXTAREA'||tag==='SELECT')return;const k=ev.key.toLowerCase();if(k==='k')this.ui.openPanel('skills');else if(k==='m')this.ui.openPanel('map');else if(k==='g')this.ui.openPanel('crafting');else if(k==='b')this.ui.openPanel('codex');else if(k==='o')this.ui.openPanel('settings');else if(this.state.mode==='combat'&&/^[1-6]$/.test(k)){const a=this.progression.combatAbilities().filter(x=>x.id!=='basic_attack')[Number(k)-1];if(a)this.combat.playerAction(a.id);}});}
  defaultSettings(){return{difficulty:'adventurer',uiScale:1,highContrast:false,reducedMotion:false,tutorials:true,autosave:true,musicEnabled:true,musicVolume:.34,effectsVolume:.65};}
  initializeExpansionState(){const s=this.state,p=s.player;s.settings={...this.defaultSettings(),...(s.settings||{})};s.reputation={wardens:0,wayfarers:0,veil:0,...(s.reputation||{})};s.story={chapter:1,title:'The Last Lantern',summary:'The roads beyond Haven are awakening, and three factions disagree about why.',choices:{},...(s.story||{})};s.lore||={};s.bestiary||={};s.tutorialsSeen||={};s.world.visited||={};s.world.discoveries||={};s.world.steps||=0;s.world.time=s.world.time??8;s.world.weather||='clear';p.talentPoints=p.talentPoints||0;p.talents||=[];p.abilityLoadout||=[];}
  newGame(build){super.newGame(build);this.initializeExpansionState();this.recalculatePlayer();this.ui.applySettings();this.saveGame(true);setTimeout(()=>this.tutorial('welcome','Haven is your hub. Explore buildings, speak with residents, track quests in the Journal, and prepare up to six abilities in Skills. Click any reachable tile to path there.'),300);}
  migrateState(){super.migrateState();this.initializeExpansionState();}
  loadGame(){super.loadGame();if(this.state){this.initializeExpansionState();this.recalculatePlayer();this.ui.applySettings();this.ui.updateHud();this.toast('Save loaded and migrated to the Tenfold Edition.');}}
  recalculatePlayer(){super.recalculatePlayer();if(!this.state||!this.talents)return;const p=this.state.player;for(const stat of Object.keys(p.effectiveStats||{}))p.effectiveStats[stat]+=this.talents.statBonus(stat);p.maxHp+=this.talents.bonus('hp');p.maxMana+=this.talents.bonus('mana');p.maxStamina+=this.talents.bonus('stamina');p.ac+=this.talents.bonus('ac');p.gearBonuses.bonusDamage=(p.gearBonuses.bonusDamage||0);p.hp=AO.Util.clamp(p.hp,0,p.maxHp);p.mana=AO.Util.clamp(p.mana,0,p.maxMana);p.stamina=AO.Util.clamp(p.stamina,0,p.maxStamina);}
  performRest(kind,cost=0){super.performRest(kind,cost);if(!this.state)return;const rolls=['clear','clear','rain','fog',this.state.rest.day>5?'emberfall':'clear'];this.state.world.weather=rolls[AO.Util.rand(0,rolls.length-1)];this.state.world.time=kind==='inn'?7:6.5;this.ui.updateHud();}
  tutorial(id,text){if(!this.state?.settings?.tutorials||this.state.tutorialsSeen[id])return;this.state.tutorialsSeen[id]=true;this.state.mode='dialogue';this.ui.dialogue('Guide',text,[{label:'Understood',action:()=>this.ui.closeDialogue()}],null,'Tutorial');}
  updateNearbyPrompt(){
    if(!this.state||!this.ui.e.nearbyPrompt)return;
    const pos=this.world.playerPos(),geometry=AO.EntityGeometry,distance=entity=>geometry?geometry.distance(pos,entity,true):AO.Util.dist(pos,entity),priority=entity=>entity.type==='door'?0:entity.type==='npc'?1:entity.type==='enemy'?2:3;
    const near=this.world.entities.filter(entity=>!entity.hidden&&entity.type!=='portal'&&distance(entity)<=1).sort((a,b)=>priority(a)-priority(b)||distance(a)-distance(b))[0];
    if(near){const label=near.name||near.label||near.title||AO.Util.title(near.kind||near.type);this.ui.e.nearbyPrompt.innerHTML=`Press <kbd>E</kbd> to interact with <strong>${label}</strong>.`;}
    else this.ui.e.nearbyPrompt.textContent='Move near a person, door, object, or discovery to interact.';
  }
  chooseCouncil(faction,npc){this.state.story.choices.council=faction;this.reputation.add(faction,35);const rewards={wardens:'warden_signet',wayfarers:'wayfarer_compass',veil:'veil_lens'};this.inventory.add(rewards[faction],1);this.log(`Haven’s council follows the ${AO.FACTIONS[faction].name}.`);this.quests.complete('lantern_council');this.state.story.title='The Crown Beneath the World';this.state.story.summary='The council has chosen a path. Something beneath Emberwatch has answered.';this.ui.closeDialogue();this.saveGame(true);}
  dialogue(npc){const council=this.quests.state('lantern_council');if(npc.id==='mira'&&council?.status==='ready'&&!this.state.story?.choices?.council){this.state.mode='dialogue';this.state.dialogueNpc='mira';this.ui.dialogue(npc.name,'The recovered relics could fortify Haven, reopen the eastern roads, or reveal the truth of the vanished stars. Mira asks which future deserves the risk.',[{label:'Entrust the relics to the Lantern Wardens.',action:()=>this.chooseCouncil('wardens',npc)},{label:'Use them to reopen the roads with the Wayfarer Compact.',action:()=>this.chooseCouncil('wayfarers',npc)},{label:'Give them to the Scholars of the Veil.',action:()=>this.chooseCouncil('veil',npc)},{label:'I need more time.',action:()=>this.ui.closeDialogue()}],npc.visual,'A Choice for Haven');return;}super.dialogue(npc);const extra={sable:{label:'Ask what lies beneath the fen.',text:'“A road, a city, and a promise. All three drowned. Only the promise keeps moving.”'},fenric:{label:'Ask why Emberwatch fell.',text:'“The signal showed a thirteenth star. The capital ordered us to extinguish it. We obeyed, and the road began burning anyway.”'},eris:{label:'Ask about the vanished stars.',text:'“They did not vanish. Someone convinced the world to stop remembering them.”'}}[npc.id];if(extra&&this.ui.e.dialogueChoices){const b=document.createElement('button');b.textContent=extra.label;b.onclick=()=>this.ui.dialogue(npc.name,extra.text,[{label:'Back',action:()=>this.dialogue(npc)}],npc.visual,npc.title);this.ui.e.dialogueChoices.insertBefore(b,this.ui.e.dialogueChoices.lastElementChild);}}
};
