/* Thousandfold Realms v1.4.2 — labeled, keyed, terrain-aware cartography. */
AO.Cartography={
  colors:{
    grass:'#657660',flower_patch:'#718061',path:'#a28d63',cobble:'#85837b',bridge:'#9a7148',water:'#3e7586',lilywater:'#497f78',shallow_water:'#638d87',reeds:'#62765d',tree:'#2d4935',shrub:'#496347',rocks:'#666864',moss_stone:'#657267',roof:'#694946',woodfloor:'#8b694d',woodwall:'#49372e',rug:'#78555a',stonewall:'#34393b',bar:'#68472e',stage:'#76513e',cellarfloor:'#4c4841',stonefloor:'#62615d',forgefloor:'#4f3d35',magicfloor:'#514b69',rune:'#625a80',chapelfloor:'#706b61',altar:'#857860',cavefloor:'#4f5557',cryptfloor:'#4b4948',cliff_face:'#424849',stairs:'#8a806e',waterfall:'#78abb6',waterfall_pool:'#4d8290'}
};
const CartographyBaseUI=AO.UI;
AO.UI=class extends CartographyBaseUI{
  constructor(game){super(game);this.mapLayers={services:true,npcs:true,enemies:true,discoveries:true};}
  mapTileColor(tile){return AO.Cartography.colors[tile]||'#5c625d';}
  mapKnown(x,y,large){const id=this.game.state.world.mapId,visited=this.game.state.world.visited?.[id]||{},charted=['haven','inn','inn_upper','tavern','general_store','forge','arcane_shop','chapel'].includes(id);return charted||!!visited[AO.Util.key(x,y)]||large&&this.game.state.settings?.revealMap===true;}
  mapMarkerStyle(kind){return({player:['#fff','#17191d'],npc:['#e9c56a','#342a17'],enemy:['#dd6d65','#3b1717'],portal:['#79c2df','#17323e'],discovery:['#c691df','#2d1838'],door:['#c79251','#3d2918'],service:['#e5b85d','#372b16'],inn:['#e8bd66','#382c18'],arcane:['#9ed9e5','#18343b'],tavern:['#e7af62','#3b2816'],shop:['#b7d27f','#26351c'],chapel:['#f0d783','#3d351c'],forge:['#e3a069','#3b2418'],square:['#eed78a','#38311d'],exit:['#78bed8','#18313b'],bridge:['#c59a60','#372719'],water:['#70b3c5','#18343c'],highground:['#b9aa8d','#343029'],danger:['#df7568','#3b1918'],rooms:['#c8b18b','#342d22'],hearth:['#e49b55','#3a2116'],stairs:['#bda277','#342a1e'],stage:['#d39d72','#382319']})[kind]||['#b8c3b4','#202823'];}
  drawMapTexture(ctx,x,y,w,h,tile,large){
    const color=this.mapTileColor(tile);ctx.fillStyle=color;ctx.fillRect(x,y,w+.5,h+.5);if(!large)return;
    const hash=(Math.floor(x/w)*17+Math.floor(y/h)*31)%11;ctx.save();ctx.globalAlpha=.32;
    if(tile==='tree'||tile==='shrub'){ctx.fillStyle='#1d3426';ctx.beginPath();ctx.arc(x+w*.35,y+h*.45,Math.max(2,w*.18),0,Math.PI*2);ctx.arc(x+w*.67,y+h*.35,Math.max(2,w*.2),0,Math.PI*2);ctx.fill();ctx.fillStyle='#7c946d';ctx.fillRect(x+w*.48,y+h*.58,Math.max(1,w*.06),h*.23);}
    else if(['water','lilywater','shallow_water','waterfall_pool'].includes(tile)){ctx.strokeStyle='#a4d3dc';ctx.lineWidth=1;for(let i=0;i<2;i++){ctx.beginPath();ctx.moveTo(x+w*(.12+i*.25),y+h*(.35+i*.3));ctx.lineTo(x+w*(.48+i*.2),y+h*(.35+i*.3));ctx.stroke();}}
    else if(['path','cobble','stonefloor','chapelfloor'].includes(tile)){ctx.strokeStyle='#312e29';ctx.lineWidth=1;ctx.strokeRect(x+2,y+2,w*.45,h*.38);ctx.strokeRect(x+w*.5,y+h*.48,w*.42,h*.38);}
    else if(tile==='grass'||tile==='flower_patch'){ctx.fillStyle=tile==='flower_patch'?'#e2bb83':'#95a487';ctx.fillRect(x+w*(.2+hash*.04%0.5),y+h*.6,Math.max(1,w*.05),Math.max(2,h*.18));if(tile==='flower_patch')ctx.fillRect(x+w*.6,y+h*.28,Math.max(2,w*.09),Math.max(2,h*.09));}
    else if(['stonewall','woodwall','cliff_face','roof'].includes(tile)){ctx.fillStyle='rgba(255,255,255,.18)';ctx.fillRect(x+1,y+1,w-2,Math.max(2,h*.14));ctx.fillStyle='rgba(0,0,0,.28)';ctx.fillRect(x+1,y+h*.76,w-2,h*.2);}
    ctx.restore();
  }
  drawMapMarker(ctx,px,py,size,kind,label='',large=false,occupied=[]){
    const [fill,stroke]=this.mapMarkerStyle(kind);ctx.save();ctx.fillStyle=stroke;ctx.beginPath();ctx.arc(px,py,size+2,0,Math.PI*2);ctx.fill();ctx.fillStyle=fill;ctx.beginPath();ctx.arc(px,py,size,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.72)';ctx.lineWidth=1;ctx.stroke();
    if(large&&label){ctx.font='bold 11px Courier New';const tw=ctx.measureText(label).width+12;let bx=AO.Util.clamp(px-tw/2,4,ctx.canvas.width-tw-4),by=AO.Util.clamp(py-size-19,4,ctx.canvas.height-20),box={x:bx,y:by,w:tw,h:16};for(let n=0;n<5&&occupied.some(o=>!(box.x+box.w<o.x||o.x+o.w<box.x||box.y+box.h<o.y||o.y+o.h<box.y));n++){box.y+=18;by=box.y;}occupied.push(box);ctx.fillStyle='rgba(8,12,13,.88)';ctx.fillRect(box.x,box.y,box.w,box.h);ctx.strokeStyle=fill;ctx.strokeRect(box.x+.5,box.y+.5,box.w-1,box.h-1);ctx.fillStyle='#f1ead9';ctx.textAlign='center';ctx.fillText(label,box.x+box.w/2,box.y+11);}
    ctx.restore();
  }
  drawMiniMap(canvas,large=false){
    if(!canvas||!this.game.world.map)return;const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,sx=w/AO.CONFIG.mapWidth,sy=h/AO.CONFIG.mapHeight,id=this.game.state.world.mapId,visited=this.game.state.world.visited?.[id]||{},knownCount=Object.keys(visited).length;ctx.clearRect(0,0,w,h);ctx.fillStyle='#0b1012';ctx.fillRect(0,0,w,h);
    for(let y=0;y<AO.CONFIG.mapHeight;y++)for(let x=0;x<AO.CONFIG.mapWidth;x++){const known=this.mapKnown(x,y,large),tile=this.game.world.grid[y]?.[x];if(known)this.drawMapTexture(ctx,x*sx,y*sy,Math.ceil(sx),Math.ceil(sy),tile,large);else{ctx.fillStyle='#111619';ctx.fillRect(x*sx,y*sy,Math.ceil(sx),Math.ceil(sy));if(large&&((x+y)%3===0)){ctx.fillStyle='rgba(255,255,255,.025)';ctx.fillRect(x*sx,y*sy,Math.ceil(sx),Math.ceil(sy));}}}
    if(large){ctx.strokeStyle='rgba(236,216,166,.14)';ctx.lineWidth=1;for(let x=0;x<=AO.CONFIG.mapWidth;x+=5){ctx.beginPath();ctx.moveTo(x*sx,0);ctx.lineTo(x*sx,h);ctx.stroke();}for(let y=0;y<=AO.CONFIG.mapHeight;y+=5){ctx.beginPath();ctx.moveTo(0,y*sy);ctx.lineTo(w,y*sy);ctx.stroke();}}
    const occupied=[],landmarks=AO.MAP_LANDMARKS?.[id]||[];for(const lm of landmarks){if(!this.mapLayers.services&&!['exit','danger'].includes(lm.kind))continue;this.drawMapMarker(ctx,(lm.x+.5)*sx,(lm.y+.5)*sy,large?5:2.4,lm.kind,lm.label,large,occupied);}
    for(const e of this.game.world.entities.filter(e=>!e.hidden)){const known=this.mapKnown(e.x,e.y,large);if(!known)continue;if(e.type==='npc'&&this.mapLayers.npcs)this.drawMapMarker(ctx,(e.x+.5)*sx,(e.y+.5)*sy,large?4:2,'npc',large?e.name:'',large,occupied);else if(e.type==='enemy'&&this.mapLayers.enemies)this.drawMapMarker(ctx,(e.x+.5)*sx,(e.y+.5)*sy,large?4:2,'enemy',large?e.name:'',large,occupied);else if(e.type==='portal'&&!landmarks.some(l=>l.kind==='exit'&&Math.abs(l.x-e.x)+Math.abs(l.y-e.y)<=2))this.drawMapMarker(ctx,(e.x+.5)*sx,(e.y+.5)*sy,large?5:2.5,'portal',large?(e.label||'Exit'):'',large,occupied);else if(e.type==='discovery'&&this.mapLayers.discoveries)this.drawMapMarker(ctx,(e.x+.5)*sx,(e.y+.5)*sy,large?4:2,'discovery',large?(e.title||'Discovery'):'',large,occupied);}
    this.drawMapMarker(ctx,(this.game.state.world.x+.5)*sx,(this.game.state.world.y+.5)*sy,large?6:3,'player',large?'YOU ARE HERE':'',large,occupied);
    ctx.save();ctx.fillStyle='rgba(8,11,12,.78)';ctx.fillRect(large?12:4,large?12:4,large?92:34,large?43:18);ctx.strokeStyle='rgba(221,190,110,.55)';ctx.strokeRect((large?12:4)+.5,(large?12:4)+.5,(large?92:34)-1,(large?43:18)-1);ctx.fillStyle='#e8c56e';ctx.textAlign='center';ctx.font=large?'bold 14px Courier New':'bold 8px Courier New';ctx.fillText('N',large?58:21,large?28:13);ctx.beginPath();ctx.moveTo(large?58:21,large?31:15);ctx.lineTo(large?52:18,large?45:20);ctx.lineTo(large?64:24,large?45:20);ctx.closePath();ctx.fill();ctx.restore();
    if(large){ctx.save();ctx.fillStyle='rgba(8,11,12,.78)';ctx.fillRect(w-178,h-35,166,23);ctx.fillStyle='#d7cba9';ctx.font='10px Courier New';ctx.textAlign='right';const explored=Math.min(100,Math.round(knownCount/(AO.CONFIG.mapWidth*AO.CONFIG.mapHeight)*100)),charted=['haven','inn','inn_upper','tavern','general_store','forge','arcane_shop','chapel'].includes(id)?100:explored;ctx.fillText(`Mapped ${charted}% • Explored ${explored}%`,w-20,h-20);ctx.restore();}
  }
  renderMap(){
    this.e.panelTitle.textContent=`Map — ${this.game.world.map.name}`;const known=Object.keys(this.game.state.world.visited?.[this.game.state.world.mapId]||{}).length,explored=Math.min(100,Math.round(known/(AO.CONFIG.mapWidth*AO.CONFIG.mapHeight)*100)),charted=['haven','inn','inn_upper','tavern','general_store','forge','arcane_shop','chapel'].includes(this.game.state.world.mapId)?100:explored;
    this.e.panelBody.innerHTML=`<div class="atlas-page"><section class="atlas-map"><div class="atlas-toolbar"><strong>${this.game.world.map.name}</strong><span>${charted}% mapped • ${explored}% explored</span><label><input type="checkbox" data-map-layer="services" ${this.mapLayers.services?'checked':''}> Landmarks</label><label><input type="checkbox" data-map-layer="npcs" ${this.mapLayers.npcs?'checked':''}> People</label><label><input type="checkbox" data-map-layer="enemies" ${this.mapLayers.enemies?'checked':''}> Threats</label><label><input type="checkbox" data-map-layer="discoveries" ${this.mapLayers.discoveries?'checked':''}> Discoveries</label></div><canvas id="largeMap" width="900" height="540" aria-label="Detailed labeled map of ${this.game.world.map.name}"></canvas></section><aside class="atlas-key"><h3>Map Key</h3><div class="map-key-list"><span><i class="key-dot player"></i>You</span><span><i class="key-dot landmark"></i>Named landmark or service</span><span><i class="key-dot npc"></i>Resident or traveler</span><span><i class="key-dot enemy"></i>Known hostile</span><span><i class="key-dot exit"></i>Road, stair, or exit</span><span><i class="key-dot discovery"></i>Discovery</span><span><i class="key-tile path"></i>Road / walkable route</span><span><i class="key-tile forest"></i>Dense cover / wall</span><span><i class="key-tile water"></i>Water</span></div><h3>Travel Notes</h3><p>${this.game.world.map.allowCamp?'Camping is permitted in this region.':'Rest requires an inn, bed, or designated campsite here.'}</p><p><strong>${charted}%</strong> of this map is available.<br><strong>${known}</strong> tiles personally explored.<br><strong>${Object.keys(this.game.state.world.discoveries||{}).length}</strong> discoveries recorded across the world.</p><h3>Current Position</h3><p>Grid ${this.game.state.world.x+1}, ${this.game.state.world.y+1}. The white marker indicates your exact position.</p></aside></div>`;
    const canvas=document.getElementById('largeMap'),redraw=()=>this.drawMiniMap(canvas,true);redraw();for(const input of this.e.panelBody.querySelectorAll('[data-map-layer]'))input.onchange=()=>{this.mapLayers[input.dataset.mapLayer]=input.checked;redraw();};
  }
};
