AO.UI = class {
  constructor(game){
    this.game=game;this.selectedRace='human';this.selectedRaceGroup='all';this.selectedClass='vanguard';this.selectedBackground='outlander';this.creatorAppearance={hairColor:'#29252a',eyeColor:'#65a8cf',accentColor:'#557a96',hairStyle:'natural',frame:'standard',mark:'none'};this.creatorStats={str:8,dex:8,con:8,int:8,wis:8,cha:8};this.pointBudget=24;this.currentShop=null;
    const by=id=>document.getElementById(id);this.e={
      creator:by('creator'),gameScreen:by('gameScreen'),continueBtn:by('continueBtn'),heroName:by('heroName'),preview:by('previewCanvas'),raceFilters:by('raceFilters'),raceChoices:by('raceChoices'),classChoices:by('classChoices'),backgroundChoices:by('backgroundChoices'),appearanceChoices:by('appearanceChoices'),creatorStats:by('creatorStats'),points:by('pointsRemaining'),summary:by('buildSummary'),recommended:by('recommendedBtn'),begin:by('beginBtn'),
      location:by('locationName'),hudPortrait:by('hudPortrait'),hudName:by('hudName'),hudBuild:by('hudBuild'),hudLevel:by('hudLevel'),hpText:by('hpText'),hpBar:by('hpBar'),manaText:by('manaText'),manaBar:by('manaBar'),staminaText:by('staminaText'),staminaBar:by('staminaBar'),xpText:by('xpText'),xpBar:by('xpBar'),gold:by('goldText'),ac:by('acText'),day:by('dayText'),tracked:by('trackedQuest'),objective:by('objectiveText'),eventLog:by('eventLog'),restedPanel:by('restedPanel'),restedText:by('restedText'),campBtn:by('campBtn'),
      panel:by('panelOverlay'),panelTitle:by('panelTitle'),panelBody:by('panelBody'),closePanel:by('closePanel'),
      dialogue:by('dialogueOverlay'),dialoguePortrait:by('dialoguePortrait'),dialogueSpeaker:by('dialogueSpeaker'),dialogueTitle:by('dialogueTitle'),dialogueText:by('dialogueText'),dialogueChoices:by('dialogueChoices'),
      combat:by('combatOverlay'),combatPlayer:by('combatPlayer'),combatEnemy:by('combatEnemy'),enemyName:by('enemyName'),combatPlayerName:by('combatPlayerName'),combatPlayerHp:by('combatPlayerHp'),combatEnemyHp:by('combatEnemyHp'),combatEnemyHpText:by('combatEnemyHpText'),combatActions:by('combatActions'),combatItems:by('combatItems'),combatLog:by('combatLog'),combatStatuses:by('combatStatuses'),combatTurnInfo:by('combatTurnInfo'),flee:by('fleeBtn'),
      toast:by('toast'),level:by('levelOverlay'),levelTitle:by('levelTitle'),levelText:by('levelText'),levelClose:by('levelClose'),defeat:by('defeatOverlay'),defeatLoad:by('defeatLoad'),defeatNew:by('defeatNew')
    };
  }
  init(){
    this.renderCreator();this.e.continueBtn.classList.toggle('hidden',!AO.SaveManager.exists());this.e.recommended.onclick=()=>this.setRecommended();this.e.begin.onclick=()=>this.begin();this.e.continueBtn.onclick=()=>this.game.loadGame();this.e.closePanel.onclick=()=>this.closePanel();this.e.flee.onclick=()=>this.game.combat.flee();this.e.levelClose.onclick=()=>this.e.level.classList.add('hidden');this.e.defeatNew.onclick=()=>location.reload();this.e.campBtn.onclick=()=>this.game.offerCamp();
    for(const b of document.querySelectorAll('[data-panel]'))b.onclick=()=>this.openPanel(b.dataset.panel);document.getElementById('saveBtn').onclick=()=>this.game.saveGame();document.getElementById('loadBtn').onclick=()=>this.game.loadGame();
  }
  pointCost(score){return score<=13?score-8:score===14?7:9;}
  usedPoints(){return Object.values(this.creatorStats).reduce((n,s)=>n+this.pointCost(s),0);}
  renderCreator(){
    if(this.e.raceFilters){this.e.raceFilters.innerHTML=Object.entries(AO.RACE_CATEGORIES).map(([id,name])=>`<button class="race-filter ${this.selectedRaceGroup===id?'selected':''}" data-race-group="${id}">${name}</button>`).join('');for(const b of this.e.raceFilters.querySelectorAll('[data-race-group]'))b.onclick=()=>{this.selectedRaceGroup=b.dataset.raceGroup;this.renderCreator();};}
    this.e.raceChoices.innerHTML='';const visibleRaces=Object.values(AO.RACES).filter(r=>this.selectedRaceGroup==='all'||r.category===this.selectedRaceGroup);for(const r of visibleRaces){const d=document.createElement('div');d.className='choice-card race-choice'+(r.id===this.selectedRace?' selected':'');d.innerHTML=`<div class="race-card-layout"><canvas width="72" height="78" aria-hidden="true"></canvas><div><div class="race-card-head"><h3>${r.name}</h3><span class="size-badge">${AO.Util.title(r.size)}</span></div><div class="sub">${r.subtitle}</div><p>${r.description}</p><div class="bonus">${r.trait}</div></div></div>`;const rc=d.querySelector('canvas').getContext('2d');rc.imageSmoothingEnabled=false;rc.fillStyle='#101418';rc.fillRect(0,0,72,78);AO.SpriteFactory.character(rc,13,9,AO.Util.visualFor(r.visual,this.creatorAppearance),AO.CLASSES[this.selectedClass].visual,1.45);d.onclick=()=>{this.selectedRace=r.id;this.renderCreator();};this.e.raceChoices.append(d);}
    this.e.classChoices.innerHTML='';for(const c of Object.values(AO.CLASSES)){const d=document.createElement('div');d.className='choice-card'+(c.id===this.selectedClass?' selected':'');d.innerHTML=`<h3>${c.name}</h3><div class="sub">${c.role}</div><p>${c.description}</p><div class="bonus">Primary: ${c.primary.toUpperCase()} • ${c.resource}</div>`;d.onclick=()=>{this.selectedClass=c.id;this.renderCreator();};this.e.classChoices.append(d);}
    this.e.backgroundChoices.innerHTML='';for(const bg of Object.values(AO.BACKGROUNDS)){const d=document.createElement('div');d.className='choice-card compact'+(bg.id===this.selectedBackground?' selected':'');d.innerHTML=`<h3>${bg.name}</h3><div class="sub">${bg.subtitle}</div><p>${bg.description}</p><div class="bonus">${bg.trait}</div>`;d.onclick=()=>{this.selectedBackground=bg.id;this.renderCreator();};this.e.backgroundChoices.append(d);}
    const options=AO.APPEARANCE_OPTIONS,swatches=(kind,list,current)=>`<div class="appearance-row"><strong>${AO.Util.title(kind)}</strong><div>${list.map(o=>`<button class="appearance-swatch ${current===(o.color||o.id)?'selected':''}" data-look="${kind}" data-value="${o.color||o.id}" title="${o.name}" ${o.color?`style="--swatch:${o.color}"`:''}>${o.color?'':o.name}</button>`).join('')}</div></div>`;
    this.e.appearanceChoices.innerHTML=swatches('hairColor',options.hair,this.creatorAppearance.hairColor)+swatches('eyeColor',options.eyes,this.creatorAppearance.eyeColor)+swatches('accentColor',options.accent,this.creatorAppearance.accentColor)+swatches('hairStyle',options.hairStyles,this.creatorAppearance.hairStyle)+swatches('frame',options.frames,this.creatorAppearance.frame)+swatches('mark',options.marks,this.creatorAppearance.mark);for(const b of this.e.appearanceChoices.querySelectorAll('[data-look]'))b.onclick=()=>{this.creatorAppearance[b.dataset.look]=b.dataset.value;this.renderCreator();};
    const names={str:'Strength',dex:'Dexterity',con:'Constitution',int:'Intelligence',wis:'Wisdom',cha:'Charisma'};this.e.creatorStats.innerHTML='';for(const [id,label] of Object.entries(names)){const row=document.createElement('div');row.className='creator-stat';row.innerHTML=`<span>${label}</span><button data-op="-">−</button><strong>${this.creatorStats[id]}</strong><button data-op="+">+</button>`;row.querySelector('[data-op="-"]').onclick=()=>this.changeCreatorStat(id,-1);row.querySelector('[data-op="+"]').onclick=()=>this.changeCreatorStat(id,1);this.e.creatorStats.append(row);}
    const remain=this.pointBudget-this.usedPoints();this.e.points.textContent=`${remain} points remaining`;this.e.begin.disabled=remain<0;const r=AO.RACES[this.selectedRace],c=AO.CLASSES[this.selectedClass],bg=AO.BACKGROUNDS[this.selectedBackground];this.e.summary.innerHTML=`<strong>${r.name} ${c.name}</strong><br>${r.lineage} • ${AO.Util.title(r.size)} • ${bg.name}<br><span>${r.trait}<br>${bg.trait}</span>`;this.drawPreview();
  }
  changeCreatorStat(stat,dir){const old=this.creatorStats[stat],next=AO.Util.clamp(old+dir,8,15);if(next===old)return;const nextUsed=this.usedPoints()-this.pointCost(old)+this.pointCost(next);if(nextUsed>this.pointBudget)return;this.creatorStats[stat]=next;this.renderCreator();}
  setRecommended(){this.creatorStats=AO.Util.deepCopy(AO.CLASSES[this.selectedClass].baseStats);this.renderCreator();}
  drawPreview(){const ctx=this.e.preview.getContext('2d'),race=AO.RACES[this.selectedRace];ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,320,320);ctx.fillStyle='#172126';ctx.fillRect(0,0,320,320);for(let y=0;y<320;y+=32)for(let x=0;x<320;x+=32){const water=y>224&&x>160;ctx.fillStyle=water?((x/32+y/32)%2?'#315d69':'#2c5662'):y>192?((x/32+y/32)%2?'#6f6550':'#776c55'):((x/32+y/32)%2?'#405542':'#465b47');ctx.fillRect(x,y,32,32);if(water){ctx.fillStyle='rgba(194,232,239,.22)';ctx.fillRect(x+5,y+10,18,2);}else if((x+y)%96===0){ctx.fillStyle='#71845e';ctx.fillRect(x+9,y+19,2,8);ctx.fillStyle='#cf8fa4';ctx.fillRect(x+6,y+17,8,4);}}ctx.fillStyle='#3b3130';ctx.fillRect(0,0,320,42);ctx.fillStyle='#6b4b3a';for(let x=0;x<320;x+=40){ctx.fillRect(x+2,8,36,25);ctx.fillStyle='#9b6e4c';ctx.fillRect(x+5,11,30,2);ctx.fillStyle='#6b4b3a';}ctx.fillStyle='#8e7958';ctx.fillRect(36,175,170,18);ctx.fillStyle='#a79066';ctx.fillRect(42,180,158,5);ctx.fillStyle='#704e32';ctx.fillRect(224,84,8,124);ctx.fillStyle='#d99b47';ctx.fillRect(217,74,22,18);ctx.fillStyle='#ffe29a';ctx.fillRect(222,78,12,10);AO.SpriteFactory.character(ctx,80,45,AO.Util.visualFor(race.visual,this.creatorAppearance),AO.CLASSES[this.selectedClass].visual,5);ctx.fillStyle='rgba(8,10,12,.72)';ctx.fillRect(12,270,296,36);ctx.fillStyle='#f0c66e';ctx.font='bold 14px Courier New';ctx.fillText(`${race.name} • ${AO.Util.title(race.size)} • ${race.lineage}`,22,292);}
  begin(){const name=this.e.heroName.value.trim()||'Nameless';this.game.newGame({name,raceId:this.selectedRace,classId:this.selectedClass,backgroundId:this.selectedBackground,appearance:AO.Util.deepCopy(this.creatorAppearance),stats:AO.Util.deepCopy(this.creatorStats)});}
  showGame(){this.e.creator.classList.add('hidden');this.e.gameScreen.classList.remove('hidden');}
  setLocation(name){this.e.location.textContent=name;}
  explorationObjective(){
    const id=this.game.state?.world?.mapId,map=this.game.world?.map;
    const objectives={
      haven:'Explore Haven, enter its storefronts, and speak with residents.',
      wilds:'Follow the eastern road through Whisperwood, or investigate its northern trails.',
      southwood_trail:'Follow the road east toward Mosswater Crossing.',
      mosswater_crossing:'Cross Mosswater and keep to the eastbound road.',
      ambermeadow:'Continue east through Ambermeadow toward Eastwatch.',
      eastwatch_approach:'Pass Eastwatch and follow the road toward Aurelia.',
      lantern_road:'Follow Lantern Road toward Aurelia.',
      lantern_mine:'Explore the abandoned mine or return to Whisperwood.',
      crypt:'Explore the Ashen Crypt or return to Whisperwood.'
    };
    if(objectives[id])return objectives[id];
    if(['interior','tavern','cellar','forge','arcane','chapel'].includes(map?.theme))return `Explore ${map?.name||'the building'}, speak with its residents, or return outside.`;
    return `Explore ${map?.name||'the surrounding area'} and locate the next safe route.`;
  }
  updateHud(){
    const p=this.game.state?.player;if(!p)return;const r=AO.RACES[p.raceId],c=AO.CLASSES[p.classId];this.e.hudName.textContent=p.name;this.e.hudBuild.textContent=`${r.name} ${c.name}`;this.e.hudLevel.textContent=`LEVEL ${p.level}`;
    const set=(text,bar,val,max)=>{text.textContent=`${val}/${max}`;bar.style.width=`${max?val/max*100:0}%`;};set(this.e.hpText,this.e.hpBar,p.hp,p.maxHp);set(this.e.manaText,this.e.manaBar,p.mana,p.maxMana);set(this.e.staminaText,this.e.staminaBar,p.stamina,p.maxStamina);
    const cap=this.game.progression.xpForLevel(p.level),max=p.level>=AO.CONFIG.maxLevel;this.e.xpText.textContent=max?'MAX':`${p.xp}/${cap}`;this.e.xpBar.style.width=`${max?100:p.xp/cap*100}%`;this.e.gold.textContent=p.gold;this.e.ac.textContent=p.ac;this.e.day.textContent=this.game.state.rest?.day||1;
    const rested=this.game.state.rest?.wellRestedBattles||0;this.e.restedPanel.classList.toggle('hidden',!rested);this.e.restedText.textContent=rested?`+5 HP, +3 mana/stamina • ${rested} battle(s) remaining`:'';
    const journal=this.game.quests.journal().filter(q=>q.state.status!=='complete'),tracked=journal.find(q=>q.id===this.game.state.trackedQuestId)||journal[0];if(tracked&&!this.game.state.trackedQuestId)this.game.state.trackedQuestId=tracked.id;this.e.tracked.textContent=tracked?tracked.def.name:'Explore';this.e.objective.textContent=tracked?(tracked.state.status==='ready'?`Return to ${AO.NPCS[tracked.def.giver]?.name||'the quest giver'}.`:tracked.stage?.text):this.explorationObjective();
    const ctx=this.e.hudPortrait.getContext('2d');ctx.clearRect(0,0,96,96);ctx.fillStyle='#101317';ctx.fillRect(0,0,96,96);AO.SpriteFactory.character(ctx,16,5,AO.Util.visualFor(r.visual,p.appearance),c.visual,2.1,{player:p});this.e.eventLog.innerHTML=(this.game.state.log||[]).slice(0,20).map(x=>`<div class="log-line">${x}</div>`).join('');
  }
  openPanel(type){if(!this.game.state||this.game.state.mode==='combat')return;this.game.state.mode='panel';this.e.panel.classList.remove('hidden');if(type==='inventory')this.renderInventory();if(type==='journal')this.renderJournal();if(type==='character')this.renderCharacter();}
  closePanel(){this.currentShop=null;this.e.panel.classList.add('hidden');if(this.game.state&&this.game.state.mode==='panel')this.game.state.mode='explore';}
  itemStats(item){
    const out=[];if(item.damage)out.push(`${item.damage[0]}d${item.damage[1]} damage`);if(item.ac)out.push(`+${item.ac} AC`);if(item.hp)out.push(`+${item.hp} HP`);if(item.mana)out.push(`+${item.mana} mana`);if(item.stamina)out.push(`+${item.stamina} stamina`);if(item.crit)out.push(`+${item.crit} crit`);if(item.bonusDamage)out.push(`+${item.bonusDamage} damage`);for(const [s,v] of Object.entries(item.stats||{}))out.push(`+${v} ${s.toUpperCase()}`);return out.join(' • ');
  }
  renderInventory(){
    const p=this.game.state.player;this.e.panelTitle.textContent='Inventory & Equipment';const labels={weapon:'Main Hand',offhand:'Off Hand',head:'Head',chest:'Chest',hands:'Hands',legs:'Legs',feet:'Feet',cloak:'Cloak',belt:'Belt',amulet:'Amulet',ring1:'Ring I',ring2:'Ring II'};
    const equip=AO.EQUIPMENT_SLOTS.map(slot=>{const id=p.equipment[slot],item=id?AO.ITEMS[id]:null;return `<div class="equipment-slot"><span>${labels[slot]}</span><strong>${item?(item.icon||'◆')+' '+item.name:'Empty'}</strong><small>${item?this.itemStats(item):'No item equipped'}</small>${item?`<button data-unequip="${slot}" class="tiny">Unequip</button>`:''}</div>`;}).join('');
    const items=p.inventory.map(entry=>this.itemCard(entry,false)).join('')||'<p>Your pack is empty.</p>';this.e.panelBody.innerHTML=`<div class="inventory-layout"><div><div class="inventory-summary"><strong>${p.inventory.reduce((n,e)=>n+e.qty,0)}</strong> carried items • <strong>${p.gold}</strong> gold</div><div class="item-grid">${items}</div></div><aside><h3>Equipment Paper Doll</h3><div class="equipment-grid">${equip}</div></aside></div>`;this.bindItemButtons();for(const b of this.e.panelBody.querySelectorAll('[data-unequip]'))b.onclick=()=>{this.game.inventory.unequip(b.dataset.unequip);this.renderInventory();};
  }
  itemCard(entry,shopMode=false){const item=AO.ITEMS[entry.itemId];if(!item)return'';const stats=this.itemStats(item);return `<article class="item-card"><span class="item-icon">${item.icon||'◆'}</span><h4>${item.name}${entry.qty>1?` ×${entry.qty}`:''}</h4><div class="item-type">${AO.Util.title(item.slot||item.type)}</div>${stats?`<div class="item-stats">${stats}</div>`:''}<p>${item.description}</p><div class="item-actions">${item.slot?`<button data-equip="${entry.uid}">Equip</button>`:''}${item.type==='consumable'?`<button data-use="${entry.uid}">Use</button>`:''}${shopMode&&item.type!=='quest'?`<button data-sell="${entry.uid}">Sell ${Math.max(1,Math.floor(item.value*.5))}g</button>`:''}</div></article>`;}
  bindItemButtons(){for(const b of this.e.panelBody.querySelectorAll('[data-equip]'))b.onclick=()=>{this.game.inventory.equip(b.dataset.equip);this.currentShop?this.renderShop(this.currentShop):this.renderInventory();};for(const b of this.e.panelBody.querySelectorAll('[data-use]'))b.onclick=()=>{this.game.inventory.use(b.dataset.use,false);this.currentShop?this.renderShop(this.currentShop):this.renderInventory();};for(const b of this.e.panelBody.querySelectorAll('[data-sell]'))b.onclick=()=>{this.game.inventory.sell(b.dataset.sell);this.renderShop(this.currentShop);};}
  renderJournal(){
    this.e.panelTitle.textContent='Quest Journal';const entries=this.game.quests.journal();this.e.panelBody.innerHTML=entries.length?entries.map(q=>`<article class="quest-card ${this.game.state.trackedQuestId===q.id?'tracked':''}"><div class="quest-head"><h3>${q.def.name}</h3>${q.state.status!=='complete'?`<button class="tiny" data-track="${q.id}">${this.game.state.trackedQuestId===q.id?'Tracked':'Track'}</button>`:''}</div><p>${q.def.summary}</p><p class="objective"><strong>${q.state.status==='complete'?'Completed':q.state.status==='ready'?'Ready to turn in':'Current'}:</strong> ${q.state.status==='complete'?'The oath is fulfilled.':q.state.status==='ready'?`Return to ${AO.NPCS[q.def.giver]?.name||'the quest giver'}.`:q.stage?.text||''}${q.stage?.count>1?` (${q.state.progress||0}/${q.stage.count})`:''}</p><div class="quest-reward">Rewards: ${q.def.reward.xp} XP • ${q.def.reward.gold} gold${(q.def.reward.items||[]).map(id=>` • ${AO.ITEMS[id]?.name||id}`).join('')}</div></article>`).join(''):'<p>No quests yet. The tavern is a good place to find work.</p>';for(const b of this.e.panelBody.querySelectorAll('[data-track]'))b.onclick=()=>{this.game.quests.track(b.dataset.track);this.renderJournal();};
  }
  renderCharacter(){
    const p=this.game.state.player,r=AO.RACES[p.raceId],c=AO.CLASSES[p.classId];this.e.panelTitle.textContent='Character';const gear=p.gearBonuses||{};
    this.e.panelBody.innerHTML=`<div class="character-grid"><div><canvas id="characterCanvas" width="220" height="260"></canvas><h3>${p.name}</h3><p>${r.name} ${c.name} • ${AO.BACKGROUNDS[p.backgroundId]?.name||'Outlander'}</p><p><strong>Bloodline:</strong> ${r.lineage} • ${AO.Util.title(r.size)}</p><p>${r.trait}</p><p><strong>Proficiencies:</strong> ${(p.skills||[]).map(AO.Util.title).join(', ')||'None'}</p><p><strong>Well Rested:</strong> ${this.game.state.rest.wellRestedBattles||0} battles</p><p>Unspent attribute points: <strong>${p.unspentPoints}</strong></p></div><div><h3>Attributes</h3><div class="stat-table">${Object.entries(p.stats).map(([id,v])=>{const effective=this.game.stat(id),bonus=effective-v;return`<div class="stat-box"><span>${AO.Util.title(id)}</span><strong>${effective}</strong><small>Base ${v}${bonus?` • Gear +${bonus}`:''} • Modifier ${AO.Util.statMod(effective)>=0?'+':''}${AO.Util.statMod(effective)}</small>${p.unspentPoints>0&&v<20?`<button data-stat="${id}" class="tiny">Increase</button>`:''}</div>`;}).join('')}</div><h3>Derived Combat Stats</h3><div class="derived-grid"><div>Armor <strong>${p.ac}</strong></div><div>Max Health <strong>${p.maxHp}</strong></div><div>Max Mana <strong>${p.maxMana}</strong></div><div>Max Stamina <strong>${p.maxStamina}</strong></div><div>Total Crit Bonus <strong>+${gear.crit||0}</strong></div><div>Total Damage Bonus <strong>+${gear.bonusDamage||0}</strong></div></div><h3>Unlocked Abilities</h3><div class="item-grid">${this.game.progression.unlockedAbilities().map(a=>`<article class="item-card"><span class="item-icon">${a.icon}</span><h4>${a.name}</h4><div class="item-type">Level ${a.level}</div><p>${a.description}</p></article>`).join('')}</div></div></div>`;
    const ctx=document.getElementById('characterCanvas').getContext('2d');ctx.fillStyle='#101317';ctx.fillRect(0,0,220,260);AO.SpriteFactory.character(ctx,30,30,AO.Util.visualFor(r.visual,p.appearance),c.visual,5,{player:p});for(const b of this.e.panelBody.querySelectorAll('[data-stat]'))b.onclick=()=>{this.game.progression.spendPoint(b.dataset.stat);this.renderCharacter();};
  }
  openShop(shopId){this.currentShop=shopId;this.game.state.mode='panel';this.e.panel.classList.remove('hidden');this.renderShop(shopId);}
  renderShop(shopId){
    const shop=AO.SHOPS[shopId],p=this.game.state.player;this.e.panelTitle.textContent=shop.name;const stock=shop.stock.map(id=>{const i=AO.ITEMS[id];return`<div class="shop-row"><span>${i.icon||'◆'} <strong>${i.name}</strong><br><small>${this.itemStats(i)||i.description}</small></span><strong>${i.value}g</strong><button data-buy="${id}">Buy</button></div>`;}).join(''),inv=p.inventory.map(e=>this.itemCard(e,true)).join('')||'<p>Nothing to sell.</p>';this.e.panelBody.innerHTML=`<p>You have <strong>${p.gold} gold</strong>.</p><div class="shop-layout"><section><h3>For Sale</h3><div class="shop-list">${stock}</div></section><section><h3>Your Pack</h3><div class="item-grid">${inv}</div></section></div>`;for(const b of this.e.panelBody.querySelectorAll('[data-buy]'))b.onclick=()=>{this.game.inventory.buy(b.dataset.buy);this.renderShop(shopId);};this.bindItemButtons();
  }
  dialogue(speaker,text,choices,visual=null,title='Conversation'){this.e.dialogueSpeaker.textContent=speaker;this.e.dialogueTitle.textContent=title;this.e.dialogueText.textContent=text;this.e.dialogueChoices.innerHTML='';const ctx=this.e.dialoguePortrait.getContext('2d');ctx.clearRect(0,0,160,220);ctx.fillStyle='#101317';ctx.fillRect(0,0,160,220);if(visual)AO.SpriteFactory.npc(ctx,18,25,visual,3.6);for(const ch of choices){const b=document.createElement('button');b.innerHTML=`${ch.check?`<span class="check-label">${ch.check}</span>`:''}${ch.label}`;b.onclick=ch.action;this.e.dialogueChoices.append(b);}this.e.dialogue.classList.remove('hidden');}
  closeDialogue(){this.e.dialogue.classList.add('hidden');if(this.game.state&&this.game.state.mode==='dialogue'){this.game.state.mode='explore';this.game.state.dialogueNpc=null;}}
  openCombat(){this.e.combat.classList.remove('hidden');}
  closeCombat(){this.e.combat.classList.add('hidden');}
  renderCombat(c,abilities){
    const p=this.game.state.player,r=AO.RACES[p.raceId],cl=AO.CLASSES[p.classId];this.e.enemyName.textContent=c.enemy.name;this.e.combatPlayerName.textContent=`${p.name} — ${p.hp}/${p.maxHp} HP`;this.e.combatPlayerHp.style.width=`${p.hp/p.maxHp*100}%`;this.e.combatEnemyHpText.textContent=`${c.enemy.name} — ${c.enemyHp}/${c.enemyMaxHp} HP`;this.e.combatEnemyHp.style.width=`${c.enemyHp/c.enemyMaxHp*100}%`;
    let ctx=this.e.combatPlayer.getContext('2d');ctx.clearRect(0,0,220,220);AO.SpriteFactory.character(ctx,42,35,AO.Util.visualFor(r.visual,p.appearance),cl.visual,4.2,{player:p});ctx=this.e.combatEnemy.getContext('2d');ctx.clearRect(0,0,220,220);AO.SpriteFactory.enemy(ctx,42,35,c.enemy.visual,4.2);
    this.e.combatStatuses.textContent=[...c.playerStatuses.map(s=>`You: ${AO.Util.title(s.id)}`),...c.enemyStatuses.map(s=>`${c.enemy.name}: ${AO.Util.title(s.id)}`),c.playerGuard?`Guard ${c.playerGuard}`:'',c.enemyGuard?`Enemy Guard ${c.enemyGuard}`:''].filter(Boolean).join(' • ');this.e.combatTurnInfo.textContent=`Round ${c.round} • ${c.turn==='player'?'YOUR TURN':c.enemy.name.toUpperCase()+' TURN'} • Enemy intent: ${c.intent||'Unknown'}`;
    this.e.combatActions.innerHTML=abilities.map(a=>{const cd=this.game.combat.cooldown(a.id),available=(!a.resource||this.game.combat.resourceValue(a.resource)>=a.cost)&&cd<=0;return`<button class="ability-btn" data-ability="${a.id}" ${c.busy||c.turn!=='player'||!available?'disabled':''}><strong>${a.icon} ${a.name}</strong><small>${a.description}</small><small class="cost">${cd?`Cooldown: ${cd}`:a.cost?`${a.cost} ${a.resource}`:'No cost'}</small></button>`;}).join('');for(const b of this.e.combatActions.querySelectorAll('[data-ability]'))b.onclick=()=>this.game.combat.playerAction(b.dataset.ability);
    const consumables=p.inventory.filter(e=>AO.ITEMS[e.itemId]?.type==='consumable');this.e.combatItems.innerHTML=consumables.length?consumables.map(e=>`<button data-combat-item="${e.uid}" ${c.busy?'disabled':''}>${AO.ITEMS[e.itemId].icon} ${AO.ITEMS[e.itemId].name} ×${e.qty}</button>`).join(''):'<span class="muted">No consumables</span>';for(const b of this.e.combatItems.querySelectorAll('[data-combat-item]'))b.onclick=()=>this.game.combat.useItem(b.dataset.combatItem);this.e.combatLog.innerHTML=c.log.map(x=>`<div>${x}</div>`).join('');this.e.flee.disabled=c.busy||c.turn!=='player';
  }
  toast(text){this.e.toast.textContent=text;this.e.toast.classList.remove('hidden');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>this.e.toast.classList.add('hidden'),1900);}
  showLevelUp(level){const gained=this.game.progression.unlockedAbilities().filter(a=>a.level===level).map(a=>a.name);this.e.levelTitle.textContent=`Level ${level} Reached`;this.e.levelText.textContent=`You gained ${level%4===0?3:2} attribute points${gained.length?` and unlocked ${gained.join(', ')}`:''}. Maximum level is ${AO.CONFIG.maxLevel}.`;this.e.level.classList.remove('hidden');}
  showDefeat(loadFn){this.e.defeat.classList.remove('hidden');this.e.defeatLoad.onclick=()=>{this.e.defeat.classList.add('hidden');loadFn();};}
};
